version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: colegio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=colegio
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
