# Generated by Django 5.2.1 on 2025-05-23 02:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("Otro", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "foto_perfil_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_curso", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "nivel_educativo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primaria", "Primaria"),
                            ("Secundaria", "Secundaria"),
                            ("Universidad", "Universidad"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_materia", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "codigo_materia",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "creditos",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_contratacion", models.DateField()),
                (
                    "titulo_academico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("profesion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preferencia_contacto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Email", "Email"),
                            ("Telefono", "Teléfono"),
                            ("WhatsApp", "WhatsApp"),
                            ("Cualquiera", "Cualquiera"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio_academico", models.IntegerField()),
                ("periodo", models.CharField(max_length=50)),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                (
                    "estado_inscripcion",
                    models.CharField(
                        choices=[
                            ("Activa", "Activa"),
                            ("Inactiva", "Inactiva"),
                            ("Suspendida", "Suspendida"),
                            ("Completada", "Completada"),
                            ("Retirada", "Retirada"),
                        ],
                        default="Activa",
                        max_length=20,
                    ),
                ),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.alumno",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "unique_together": {("alumno", "curso", "anio_academico", "periodo")},
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.CharField(
                        choices=[
                            ("Examen Parcial 1", "Examen Parcial 1"),
                            ("Examen Parcial 2", "Examen Parcial 2"),
                            ("Examen Final", "Examen Final"),
                            ("Proyecto", "Proyecto"),
                            ("Tarea", "Tarea"),
                            ("Participación", "Participación"),
                            ("Cuestionario", "Cuestionario"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("fecha_evaluacion", models.DateField()),
                ("comentarios_profesor", models.TextField(blank=True, null=True)),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.inscripcion",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.profesor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_asignacion", models.DateField(auto_now_add=True)),
                ("fecha_entrega_limite", models.DateField()),
                ("max_puntuacion", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("Tarea", "Tarea"),
                            ("Proyecto Individual", "Proyecto Individual"),
                            ("Proyecto Grupal", "Proyecto Grupal"),
                            ("Examen Corto", "Examen Corto"),
                            ("Práctica", "Práctica"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.profesor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Profesor", "Profesor"),
                            ("Alumno", "Alumno"),
                            ("Tutor", "Tutor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_sesion", models.DateTimeField(blank=True, null=True)),
                (
                    "alumno",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.alumno",
                    ),
                ),
                (
                    "profesor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.profesor",
                    ),
                ),
                (
                    "tutor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntregaActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrega", models.DateTimeField(auto_now_add=True)),
                (
                    "puntuacion_obtenida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("comentarios_profesor", models.TextField(blank=True, null=True)),
                (
                    "estado_entrega",
                    models.CharField(
                        choices=[
                            ("Entregado", "Entregado"),
                            ("Pendiente", "Pendiente"),
                            ("Retrasado", "Retrasado"),
                            ("Revisado", "Revisado"),
                            ("No Entregado", "No Entregado"),
                        ],
                        default="Entregado",
                        max_length=50,
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.actividadproyecto",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.alumno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de Actividad",
                "verbose_name_plural": "Entregas de Actividades",
                "unique_together": {("actividad", "alumno")},
            },
        ),
        migrations.CreateModel(
            name="Participacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "puntuacion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("comentarios", models.TextField(blank=True, null=True)),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.inscripcion",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participación",
                "verbose_name_plural": "Participaciones",
                "unique_together": {("inscripcion", "materia", "fecha", "profesor")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Presente", "Presente"),
                            ("Ausente", "Ausente"),
                            ("Tarde", "Tarde"),
                            ("Justificado", "Justificado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.inscripcion",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "unique_together": {("inscripcion", "materia", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="AsignacionCursoMateria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio_academico", models.IntegerField()),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("Semestre 1", "Semestre 1"),
                            ("Semestre 2", "Semestre 2"),
                            ("Año Completo", "Año Completo"),
                            ("Trimestre 1", "Trimestre 1"),
                            ("Trimestre 2", "Trimestre 2"),
                            ("Trimestre 3", "Trimestre 3"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.curso",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Curso y Materia",
                "verbose_name_plural": "Asignaciones de Cursos y Materias",
                "unique_together": {
                    ("curso", "materia", "profesor", "anio_academico", "periodo")
                },
            },
        ),
        migrations.CreateModel(
            name="AlumnoTutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relacion",
                    models.CharField(
                        choices=[
                            ("Padre", "Padre"),
                            ("Madre", "Madre"),
                            ("Tio", "Tío"),
                            ("Tia", "Tía"),
                            ("Abuelo", "Abuelo"),
                            ("Abuela", "Abuela"),
                            ("Tutor Legal", "Tutor Legal"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("es_contacto_principal", models.BooleanField(default=False)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.alumno",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_escolar.tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relación Alumno-Tutor",
                "verbose_name_plural": "Relaciones Alumno-Tutor",
                "unique_together": {("alumno", "tutor", "relacion")},
            },
        ),
    ]
