# Generated by Django 5.2.3 on 2025-06-17 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tarde', 'Tarde'), ('Justificado', 'Justificado')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='puntuacion',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
